apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awesome-apps.fullname" . }}-nginx
  labels:
    {{- include "awesome-apps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "awesome-apps.selectorLabels" . | nindent 6 }}
      app: nginx
  template:
    metadata:
      {{- with .Values.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "awesome-apps.selectorLabels" . | nindent 8 }}
        app: nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.nginx.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nginx.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.nginx.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.nginx.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.nginx.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.nginx.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nginx.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.nginx.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.nginx.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.nginx.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index
      volumes:
        - name: index
          configMap:
            name: {{ .Release.Name }}-index
